logging:
  level: debug
  handler: console # localfile / console

environ: test # prod / test

apps:
  prod:
    producer-app:
      input-data-path: s3a://data-ice-lake-05/master/data/source/order-app
      topic-out: &order-app-ouput-topic order-app-orders

    stg-collector-app: &stg
      topic-in: *order-app-ouput-topic
      topic-out: &stg-processor-output-topic stg-collector-app-orders
      target-tables:
        order-events: stg.order_events

    dds-collector-app: &dds
      topic-in: *stg-processor-output-topic
      topic-out: &dds-processor-output-topic dds-collector-app-orders
      target-tables:
        hubs:
          user: dds.h_user
          restaurant: dds.h_restaurant
          order: dds.h_order
          category: dds.h_category
          product: dds.h_product
        links:
          order-product: dds.l_order_product
          order-user: dds.l_order_user
          product-category: dds.l_product_category
          product-restaurant: dds.l_product_restaurant
        satelities:
          order-cost: dds.s_order_cost
          order-status: dds.s_order_status
          product-names: dds.s_product_names
          restaurant-names: dds.s_restaurant_names
          user-names: dds.s_user_names

    cdm-collector-app: &cdm
      topic-in: *dds-processor-output-topic
      target-tables:
        user_product_counters: cdm.user_product_counters
        user_category_counters: cdm.user_category_counters

  test:
    stg-collector-app:
      <<: *stg
    dds-collector-app:
      <<: *dds
    cdm-collector-app:
      <<: *cdm
