logging:
  level: debug
  handler: console # localfile / console

environ: prod # prod / test

topics:
  order-service-orders: &order-service-orders-topic order-service_orders # order-app-orders
  stg-processor-output: &stg-processor-output-topic stg-service-orders # stg-collector-app-orders

apps:
  prod:
    stg-collector-app:
      topic-in: *order-service-orders-topic
      topic-out: *stg-processor-output-topic
      target-tables:
        order-events: stg.order_events

    dds-collector-app:
      topic-in: *stg-processor-output-topic
      target-tables:
        hubs:
          user: dds.h_user
          restaurant: dds.h_restaurant
          order: dds.h_order
          category: dds.h_category
          product: dds.h_product
        links:
          order-product: dds.l_order_product
          order-user: dds.l_order_user
          product-category: dds.l_product_category
          product-restaurant: dds.l_product_restaurant
        satelities:
          order-cost: dds.s_order_cost
          order-status: dds.s_order_status
          product-names: dds.s_product_names
          restaurant-names: dds.s_restaurant_names
          user-names: dds.s_user_names

    cdm-collector-app:

  test:
    stg-collector-app:
      topic-in: *order-service-orders-topic
      topic-out: *stg-processor-output-topic
      target-tables:
        order-events: stg.order_events

    dds-collector-app:
      topic-in: *stg-processor-output-topic
      target-tables:
        hubs:
          h_category: h_category
        satelities:
        links:

    cdm-collector-app:
