version: '3.8'

networks:
  internal:
    driver: bridge

x-apps-common: &apps-common
  restart: no 
  networks:
    - internal

services:
  stg-collector-app:
    build:
      dockerfile: ./apps/stg-collector-app/Dockerfile
    container_name: stg-collector-app
    <<: *apps-common

  dds-collector-app:
    build:
      dockerfile: ./apps/dds-collector-app/Dockerfile
    container_name: dds-collector-app
    <<: *apps-common

  cdm-collector-app:
    build:
      dockerfile: ./apps/cdm-collector-app/Dockerfile
    container_name: cdm-collector-app
    <<: *apps-common

  producer-app:
    build:
      dockerfile: ./apps/producer-app/Dockerfile
    container_name: producer-app
    <<: *apps-common

  mongodb: # https://github.com/bitnami/containers/tree/main/bitnami/mongodb
    image: bitnami/mongodb:5.0.21-debian-11-r5
    ports:
      - 27017:27017
    environment:
      - MONGODB_ROOT_USER=${MONGODB_ROOT_USER}
      - MONGODB_ROOT_PASSWORD=${MONGODB_ROOT_PASSWORD}
    container_name: mongodb
    <<: *apps-common

  postgres: # https://github.com/bitnami/containers/blob/main/bitnami/postgresql
    image: bitnami/postgresql:15.4.0-debian-11-r38
    ports:
      - 5432:5432
    environment:
      - POSTGRESQL_POSTGRES_PASSWORD=${POSTGRESQL_POSTGRES_PASSWORD}
    volumes:
      - ./scripts/postgres/:/opt/scripts
    container_name: postgres
    <<: *apps-common

  kafka:  # https://github.com/bitnami/containers/tree/main/bitnami/kafka
    image: docker.io/bitnami/kafka:3.4.1-debian-11-r13
    container_name: kafka
    ports:
      - 9092:9092
    environment:
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://158.160.7.142:9092
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
    volumes:
      - ./configs/kafka/log4j.properties:/opt/bitnami/kafka/config/log4j.properties 
    <<: *apps-common

