version: '3.8'

networks:
  internal:
    driver: bridge

x-apps-common: &apps-common
  restart: no 
  networks:
    - internal

services:
  stg-collector-app:
    build:
      dockerfile: ./apps/stg-collector-app/Dockerfile
    container_name: stg-collector-app
    <<: *apps-common


  dds-collector-app:
    build:
      dockerfile: ./apps/dds-collector-app/Dockerfile
    container_name: dds-collector-app
    <<: *apps-common

