version: '3.8'

networks:
  internal:
    driver: bridge

services:
  stg-collector-app:
    image: cr.yandex/$YC_REGISTRY_ID/stg-collector-app:v20230826-r1
    container_name: stg-collector-app
    restart: no 
    networks:
      - internal
