version: '3.8'

networks:
  internal:
    driver: bridge

services:
  stg-collector-app:
    build: 
      dockerfile: docker/stg-collector-app/Dockerfile
    container_name: stg-collector-app
    command:
      - /bin/sh
      - -c
      - |
        cd /app \
        && . $(poetry env info --path)/bin/activate \
        && python /app/services/stg-collector-app/test.py
    volumes:
      - ./.:/app/.
    restart: unless-stopped
    networks:
      - internal
    environment:
      # FLASK_APP: ${STG_SERVICE_APP_NAME:-stg_service}
      # DEBUG: ${STG_SERVICE_DEBUG:-True}

      KAFKA_BOOTSTRAP_SERVERS: ${KAFKA_BOOTSTRAP_SERVERS}
      KAFKA_USERNAME: ${KAFKA_USERNAME}
      KAFKA_PASSWORD: ${KAFKA_PASSWORD}
      # KAFKA_SOURCE_TOPIC: ${KAFKA_SOURCE_TOPIC}
      # KAFKA_DESTINATION_TOPIC: ${KAFKA_STG_SERVICE_ORDERS_TOPIC}

      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      REDIS_PASSWORD: ${REDIS_PASSWORD}

      CERTIFICATE_PATH: ${CERTIFICATE_PATH}

      # PG_WAREHOUSE_HOST: ${PG_WAREHOUSE_HOST}
      # PG_WAREHOUSE_PORT: ${PG_WAREHOUSE_PORT}
      # PG_WAREHOUSE_DBNAME: ${PG_WAREHOUSE_DBNAME}
      # PG_WAREHOUSE_USER: ${PG_WAREHOUSE_USER}
      # PG_WAREHOUSE_PASSWORD: ${PG_WAREHOUSE_PASSWORD}
    